package de.caegroup.codegen;

import java.io.*;
import java.math.BigInteger;
import java.util.*;
import java.security.*;
import java.sql.Timestamp;

public class BMeta
implements Serializable, Cloneable
{
	/*----------------------------
	  structure
	----------------------------*/

	static final long serialVersionUID = 1;
	Script parent = null;
	Block block = new Block();
	String version = "";

	/*----------------------------
	  constructors
	----------------------------*/
	/**
	 * constructs a BMeta
	 */
	public BMeta(Script parent)
	{
		this.parent = parent;
	}

	/*----------------------------
	  methods 
	----------------------------*/
	public ArrayList<String> getBlock()
	{
		return this.block.getCode();
	}

	public void genCode(String type)
	{
		ArrayList<String> content = new ArrayList<String>();
		
		if(type.matches("process"))
		{
			Timestamp timestamp = new Timestamp(System.currentTimeMillis());
			
			content.add("# generated by codegen-core on "+timestamp);
			content.add("my $version = \"" + this.getVersion() + "\";");
			content.add("my $date = \"" + timestamp.toString().replaceAll("\\.\\d+", "") + "\";");
		}
		// default
		else
		{
			Timestamp timestamp = new Timestamp(System.currentTimeMillis());
			
			content.add("# generated by codegen-core on "+timestamp);
			content.add("my $version = \"[% version %]\";");
			content.add("my $date = \"[% date %]\";");
		}
		
		this.block.setOrigin("auto");
		this.block.setBlockname("meta");
		this.block.setCode(content);
	}

	/**
	 * @return the version
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * @param version the version to set
	 */
	public void setVersion(String version) {
		this.version = version;
	}
}