//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.30 at 08:18:25 PM CEST 
//


package de.caegroup.jaxb.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}match"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fromobjecttype" use="required" type="{}ResourceType" />
 *       &lt;attribute name="fromstep" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="returnfield" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="listname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="insertrule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "match"
})
@XmlRootElement(name = "init")
public class Init {

    @XmlElement(required = true)
    protected Match match;
    @XmlAttribute(name = "fromobjecttype", required = true)
    protected String fromobjecttype;
    @XmlAttribute(name = "fromstep", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fromstep;
    @XmlAttribute(name = "mandatory")
    protected Boolean mandatory;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "returnfield")
    protected String returnfield;
    @XmlAttribute(name = "listname")
    protected String listname;
    @XmlAttribute(name = "insertrule")
    protected String insertrule;

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link Match }
     *     
     */
    public Match getMatch() {
        return match;
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link Match }
     *     
     */
    public void setMatch(Match value) {
        this.match = value;
    }

    /**
     * Gets the value of the fromobjecttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromobjecttype() {
        return fromobjecttype;
    }

    /**
     * Sets the value of the fromobjecttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromobjecttype(String value) {
        this.fromobjecttype = value;
    }

    /**
     * Gets the value of the fromstep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromstep() {
        return fromstep;
    }

    /**
     * Sets the value of the fromstep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromstep(String value) {
        this.fromstep = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMandatory(Boolean value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the returnfield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnfield() {
        return returnfield;
    }

    /**
     * Sets the value of the returnfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnfield(String value) {
        this.returnfield = value;
    }

    /**
     * Gets the value of the listname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListname() {
        return listname;
    }

    /**
     * Sets the value of the listname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListname(String value) {
        this.listname = value;
    }

    /**
     * Gets the value of the insertrule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertrule() {
        return insertrule;
    }

    /**
     * Sets the value of the insertrule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertrule(String value) {
        this.insertrule = value;
    }

}
