package de.prozesskraft.codegen;

import java.io.*;
import java.math.BigInteger;
import java.util.*;
import java.security.*;

public class BSubs
implements Serializable, Cloneable
{
	/*----------------------------
	  structure
	----------------------------*/

	static final long serialVersionUID = 1;
	Script parent = null;
	Block block = new Block();

	ArrayList<String> code_printHtmlOverview = new ArrayList<String>();
	ArrayList<String> code_logit = new ArrayList<String>();
	ArrayList<String> code_logitProcess = new ArrayList<String>();
	ArrayList<String> code_readConf = new ArrayList<String>();
	ArrayList<String> code_switchConf = new ArrayList<String>();
	ArrayList<String> code_readconf = new ArrayList<String>();
	ArrayList<String> code_expandConfigToPath = new ArrayList<String>();
	ArrayList<String> code_switchconf = new ArrayList<String>();
	ArrayList<String> code_getvars = new ArrayList<String>();
	ArrayList<String> code_initlist = new ArrayList<String>();
	ArrayList<String> code_girlande = new ArrayList<String>();
	ArrayList<String> code_getsetoptionsconfigs = new ArrayList<String>();
	ArrayList<String> code_importinitcommits = new ArrayList<String>();
	ArrayList<String> code_resolve = new ArrayList<String>();
	ArrayList<String> code_commandresolve = new ArrayList<String>();
	ArrayList<String> content = new ArrayList<String>();
	/*----------------------------
	  constructors
	----------------------------*/
	public BSubs(Script parent)
	{
		this.parent = parent;
		this.initPrintHtmlOverview();
		this.initCodeLogit();
		this.initCodeLogitProcess();
		this.initCodeReadConf();
		this.initCodeExpandConfigToPath();
		this.initCodeSwitchConf();
		this.initCodeGetvars();
		this.initCodeInitlist();
		this.initCodeGirlande();
		this.initCodeGetsetoptionsconfigs();
		this.initCodeimportinitcommits();
		this.initCodeResolve();
		this.initCodeCommandresolve();
	}

	/*----------------------------
	  methods 
	----------------------------*/
	public ArrayList<String> getBlock()
	{
		return this.block.getCode();
	}

	public void genCode(String type)
	{
		ArrayList<String> content = new ArrayList<String>();
		
		if(type.matches("process"))
		{
			content.addAll(this.code_printHtmlOverview);
			content.addAll(this.code_expandConfigToPath);
			content.addAll(this.code_getvars);
			content.addAll(this.code_logitProcess);
			content.addAll(this.code_initlist);
			content.addAll(this.code_girlande);
			content.addAll(this.code_getsetoptionsconfigs);
			content.addAll(this.code_importinitcommits);
			content.addAll(this.code_resolve);
			content.addAll(this.code_commandresolve);
		}
		// default
		else
		{
			content.addAll(this.code_readconf);
			content.addAll(this.code_expandConfigToPath);
			content.addAll(this.code_switchconf);
			content.addAll(this.code_getvars);
			content.addAll(this.code_logit);
			content.addAll(this.code_getsetoptionsconfigs);
		}
		
		this.block.setOrigin("auto");
		this.block.setBlockname("subs");
		this.block.setCode(content);
	}

	private void initPrintHtmlOverview()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub printHtmlOverview");
		code.add("{");
		code.add("	#-------------------");
		code.add("	# erstellen der html tabelle zur darstellung von Meta");
		code.add("	my $html_table_meta = HTML::Table->new(");
		code.add("						-rows    => 0,");
		code.add("						-cols    => 2,");
		code.add("						-align   => 'justify',");
		code.add("						-rules   => 'all',");
		code.add("						-border  => 3,				# rahmen");
		code.add("						-bgcolor => 'white',");
		code.add("						-width   => '100%',");
		code.add("						-spacing => 5,");
		code.add("						-padding => 8,");
		code.add("						-style   => 'color: dimgray',");
		code.add("#						-head => ['woher', 'typ', 'label', 'beschreibung', 'inhalt/link'],");
		code.add("					);");
		code.add("");
		code.add("	$html_table_meta->addRow('user', $ENV{'USER'});");
		code.add("	$html_table_meta->addRow('start', $PROCESS_START);");
		code.add("	$html_table_meta->addRow('stop', $PROCESS_STOP);");
		code.add("	$html_table_meta->addRow('directory', \"<a href=\\\"\".$instancedir.\"\\\" target=\\\"_blank\\\">\".$instancedir.\"</a>\");");
		code.add("	$html_table_meta->addRow('aufruf', $FULLCALL);");
		code.add("	$html_table_meta->addRow('status', $PROCESS_STATUS);");
		code.add("	if($PROCESS_STATUS =~ m/exit=[0]/)");
		code.add("	{");
		code.add("		$html_table_meta->setCellBGColor(6, 2, 'yellowgreen');");
		code.add("	}");
		code.add("	elsif (($PROCESS_STATUS =~ m/exit=[^0]/) || ($PROCESS_STATUS =~ m/error/))");
		code.add("	{");
		code.add("		$html_table_meta->setCellBGColor(6, 2, 'tomato');");
		code.add("	}");
		code.add("	");
		code.add("");
		code.add("	#-------------------");
		code.add("	# erstellen der html tabelle zur uebersicht von INPUT");
		code.add("	my $html_table_input = HTML::Table->new(");
		code.add("						-rows    => 0,");
		code.add("						-cols    => 5,");
		code.add("						-align   => 'justify',");
		code.add("						-rules   => 'all',");
		code.add("						-border  => 3,				# rahmen");
		code.add("						-bgcolor => 'white',");
		code.add("						-width   => '100%',");
		code.add("						-spacing => 5,");
		code.add("						-padding => 8,");
		code.add("						-style   => 'color: dimgray',");
		code.add("						-head => ['woher', 'typ', 'label', 'beschreibung', 'inhalt/link'],");
		code.add("						);");
		code.add("	");
		code.add("	foreach my $refa_row (@INPUT_TABELLE)");
		code.add("	{");
		code.add("		$html_table_input->addRow(@$refa_row);");
		code.add("	}");
		code.add("	");
		code.add("	#-------------------");
		code.add("	# erstellen der html tabelle zur uebersicht von OUTPUT");
		code.add("	my $html_table_output = HTML::Table->new(");
		code.add("						-rows    => 0,");
		code.add("						-cols    => 5,");
		code.add("						-align   => 'justify',");
		code.add("						-rules   => 'all',");
		code.add("						-border  => 3,				# rahmen");
		code.add("						-bgcolor => 'white',");
		code.add("						-width   => '100%',");
		code.add("						-spacing => 5,");
		code.add("						-padding => 8,");
		code.add("						-style   => 'color: dimgray',");
		code.add("						-head => ['woher', 'typ', 'label', 'beschreibung', 'inhalt/link'],");
		code.add("						);");
		code.add("	");
		code.add("	foreach my $refa_row (@OUTPUT_TABELLE)");
		code.add("	{");
		code.add("		$html_table_output->addRow(@$refa_row);");
		code.add("	}");
		code.add("	");
		code.add("	#-------------------");
		code.add("	# erstellen der html tabelle zur darstellung von prozessschritte");
		code.add("	my $html_table_steps = HTML::Table->new(");
		code.add("						-rows    => 0,");
		code.add("						-cols    => 7,");
		code.add("						-align   => 'justify',");
		code.add("						-rules   => 'all',");
		code.add("						-border  => 3,				# rahmen");
		code.add("						-bgcolor => 'white',");
		code.add("						-width   => '100%',");
		code.add("						-spacing => 5,");
		code.add("						-padding => 8,");
		code.add("						-style   => 'color: dimgray',");
		code.add("						-head => ['rang', 'stepnamen', 'beschreibung', 'aufruf', 'dir', 'status', 'log'],");
		code.add("					);");
		code.add("	");
		code.add("	my $row = 1;");
		code.add("	foreach my $key (sort keys %STEPS_TABELLE)");
		code.add("	{");
		code.add("		$html_table_steps->addRow(${$STEPS_TABELLE{$key}}{'rang'}, ${$STEPS_TABELLE{$key}}{'stepnamen'}, ${$STEPS_TABELLE{$key}}{'beschreibung'}, ${$STEPS_TABELLE{$key}}{'aufruf'}, ${$STEPS_TABELLE{$key}}{'dir'}, ${$STEPS_TABELLE{$key}}{'status'}, ${$STEPS_TABELLE{$key}}{'log'});");
		code.add("		$row++;");
		code.add("		if (${$STEPS_TABELLE{$key}}{'status'} =~ m/exit=[^0]/)");
		code.add("		{");
		code.add("			$html_table_steps->setCellBGColor($row, 6, 'tomato');");
		code.add("		}");
		code.add("		elsif (${$STEPS_TABELLE{$key}}{'status'} =~ m/exit=[0]/)");
		code.add("		{");
		code.add("			$html_table_steps->setCellBGColor($row, 6, 'yellowgreen');");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	#-------------------");
		code.add("	# erstellen der html tabelle zur darstellung von Logging");
		code.add("	my $html_table_logging = HTML::Table->new(");
		code.add("						-rows    => 0,");
		code.add("						-cols    => 3,");
		code.add("						-align   => 'justify',");
		code.add("						-rules   => 'no',");
		code.add("						-border  => 3,				# rahmen");
		code.add("						-bgcolor => 'white',");
		code.add("						-width   => '100%',");
		code.add("						-spacing => 5,");
		code.add("						-padding => 4,");
		code.add("						-style   => 'color: dimgray',");
		code.add("						-head => ['zeit', 'level', 'log'],");
		code.add("					);");
		code.add("	");
		code.add("	$html_table_logging->setColWidth(1, 220);");
		code.add("	$html_table_logging->setColWidth(2, 50);");
		code.add("	");
		code.add("	my $row2 = 1;	# der header ist bereits die row 1");
		code.add("	foreach my $refa_row (@PROCESS_LOGGING)");
		code.add("	{");
		code.add("		$row2++;");
		code.add("		$html_table_logging->addRow(@$refa_row);");
		code.add("		if ($$refa_row[1] =~ m/warn/)");
		code.add("		{");
		code.add("			$html_table_logging->setCellBGColor($row2, 2, 'khaki');");
		code.add("		}");
		code.add("		elsif ($$refa_row[1] =~ m/error|fatal/)");
		code.add("		{");
		code.add("			$html_table_logging->setCellBGColor($row2, 2, 'tomato');");
		code.add("		}");
		code.add("	#		elsif ($$refa_row[1] =~ m/info/)");
		code.add("	#		{");
		code.add("	#			$html_table_logging->setCellBGColor($row2, 2, 'yellowgreen');");
		code.add("	#		}");
		code.add("	}");
		code.add("	");
		code.add("	#-------------------");
		code.add("	# erstellen der html tabelle zur darstellung von Backup");
		code.add("	my $html_table_backup = HTML::Table->new(");
		code.add("						-rows    => 0,");
		code.add("						-cols    => 2,");
		code.add("						-align   => 'justify',");
		code.add("						-rules   => 'all',");
		code.add("						-border  => 3,				# rahmen");
		code.add("						-bgcolor => 'white',");
		code.add("						-width   => '100%',");
		code.add("						-spacing => 5,");
		code.add("						-padding => 8,");
		code.add("						-style   => 'color: dimgray',");
		code.add("#						-head => ['woher', 'typ', 'label', 'beschreibung', 'inhalt/link'],");
		code.add("					);");
		code.add("");
		code.add("	$html_table_backup->addRow('prozess', $PROCESS_NAME);");
		code.add("	$html_table_backup->addRow('version', $version);");
		code.add("	$html_table_backup->addRow(\"prozessverantwortlicher bei $PROCESS_CUSTOMERCOMPANY\", \"<a href=\\\"mailto:$PROCESS_CUSTOMERMAIL\\\">$PROCESS_CUSTOMERNAME</a>\");");
		code.add("	(my $filenam, my $dirs, my $suf) = fileparse ($doc_path);");
		code.add("	# wenn eine doku existiert, soll sie hier gelinkt werden");
		code.add("	if(stat $doc_path)");
		code.add("	{");
		code.add("		$html_table_backup->addRow('dokumentation', \"<a href=\\\"$doc_path\\\" target=\\\"_blank\\\">$filenam</a>\");");
		code.add("	}");
		code.add("");
		code.add("	$html_table_backup->addRow('installations directory', \"<a href=\\\"\" . Cwd::realpath($installdir) . \"\\\" target=\\\"_blank\\\">\" . Cwd::realpath($installdir) . \"</a>\");");
		code.add("");
		code.add("#-------------------");
		code.add("# ausgabe in file");
		code.add("	# das stdout handle sichern und ein neues auf das ausgabefile zeigen lassen");
		code.add("	my $outfile = $instancedir . \"/README.html\";");
		code.add("	unlink($outfile);");
		code.add("	");
		code.add("	open (SAVE, \">&STDOUT\") or die \"Can't save STDOUT $!\\n\";");
		code.add("	open (STDOUT, '>', $outfile) or die \"Can't redirect STDOUT to \" . $outfile . \": $!\\n\";");
		code.add("	");
		code.add("	print \"<h1 align=\\\"center\\\">$PROCESS_NAME --version $version</h1>\\n\";");
		code.add("");
		code.add("	print \"<h2>Meta</h2>\\n\";");
		code.add("	$html_table_meta->print();");
		code.add("	");
		code.add("	print \"<h2>Input</h2>\\n\";");
		code.add("	$html_table_input->print();");
		code.add("	");
		code.add("	print \"<h2>Output</h2>\\n\";");
		code.add("	$html_table_output->print();");
		code.add("	");
		code.add("	print \"<h2>Schritte</h2>\\n\";");
		code.add("	$html_table_steps->print();");
		code.add("	");
		code.add("	print \"<h2>Logging</h2>\\n\";");
		code.add("	$html_table_logging->print();");
		code.add("	");
		code.add("	print \"<h2>Backup</h2>\\n\";");
		code.add("	$html_table_backup->print();");
		code.add("	");
		code.add("	print \"<p>Dieser automatische CAE-Prozess wurde entwickelt von <a href=\\\"mailto:$PROCESS_ARCHITECTMAIL\\\">$PROCESS_ARCHITECTNAME</a> im Auftrag von $PROCESS_CUSTOMERCOMPANY</p>\\n\";");
		code.add("	# STDOUT wiederherstellen");
		code.add("	");
		code.add("	open (STDOUT, \">&SAVE\") or die \"Can't restore STDOUT $!\\n\";");
		code.add("	close SAVE;");
		code.add("}");
		code.add("");
	
		this.code_printHtmlOverview = code;
	}
	
	private void initCodeLogit()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub logit");
		code.add("{");
		code.add("	if (scalar(@_) < 2) {die \"wrong call on subroutine 'logit'\";}");
		code.add("	my $level = shift;");
		code.add("	my $msg = shift;");
		code.add("	my $dest;");
		code.add("	if (@_)");
		code.add("	{");
		code.add("		$dest = shift;");
		code.add("	}");
		code.add("	");
		code.add("# wenn loglevel == debug, ABER --debug nicht gesetzt wurde, soll nicht geloggt werden");
		code.add("		if ( ($level eq \"debug\") &! (getOption(\"debug\") ||  getOption(\"d\")) )");
		code.add("		{");
		code.add("			return;");
		code.add("		}");
		code.add("");
		code.add("	my $timestamp = localtime(time);");
		code.add("	");
		code.add("	my $ausgabestring = '[' . $timestamp . ']:' . $level . ':' . $msg; ");
		code.add("	");
		code.add("	if (!($dest))");
		code.add("	{");
		code.add("		print STDERR $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("	elsif ($dest =~ m/^stderr$/i)");
		code.add("	{");
		code.add("		print STDERR $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("	elsif ($dest =~ m/^stdout$/i)");
		code.add("	{");
		code.add("		print STDOUT $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("	elsif (($dest) && (stat $dest))");
		code.add("	{");
		code.add("		system 'echo $ausgabestring >> $dest';");
		code.add("	}");
		code.add("	else");
		code.add("	{");
		code.add("		print STDERR 'unknown logging destination $dest (file does not exist)' . '. assuming stderr';");
		code.add("		print STDERR $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("}");
		code.add("");

		this.code_logit = code;
	}

	private void initCodeLogitProcess()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub logit");
		code.add("{");
		code.add("	if (scalar(@_) < 2) {die \"wrong call on subroutine 'logit'\";}");
		code.add("	my $level = shift;");
		code.add("	my $msg = shift;");
		code.add("	my $dest;");
		code.add("	if (@_)");
		code.add("	{");
		code.add("		$dest = shift;");
		code.add("	}");
		code.add("	");
		code.add("# wenn loglevel == debug, ABER --debug nicht gesetzt wurde, soll nicht geloggt werden");
		code.add("		if ( ($level eq \"debug\") &! (getOption(\"debug\") ||  getOption(\"d\")) )");
		code.add("		{");
		code.add("			return;");
		code.add("		}");
		code.add("");
		code.add("	my $timestamp = localtime(time);");
		code.add("	");
		code.add("	my $ausgabestring = '[' . $timestamp . ']:' . $level . ':' . $msg; ");
		code.add("	");
		code.add("	if (!($dest))");
		code.add("	{");
		code.add("		print STDERR $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("	elsif ($dest =~ m/^stderr$/i)");
		code.add("	{");
		code.add("		print STDERR $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("	elsif ($dest =~ m/^stdout$/i)");
		code.add("	{");
		code.add("		print STDOUT $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("	elsif (($dest) && (stat $dest))");
		code.add("	{");
		code.add("		system 'echo $ausgabestring >> $dest';");
		code.add("	}");
		code.add("	else");
		code.add("	{");
		code.add("		print STDERR 'unknown logging destination $dest (file does not exist)' . '. assuming stderr';");
		code.add("		print STDERR $ausgabestring.\"\\n\";");
		code.add("	}");
		code.add("");
		code.add("	push(@PROCESS_LOGGING, [$timestamp, $level, $msg]);");
		code.add("");
		code.add("}");
		code.add("");

		this.code_logitProcess = code;
	}

	private void initCodeReadConf()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub readConf");
		code.add("{");
		code.add("	my $label = shift;");
		code.add("	my $pathFromUser = shift;");
		code.add("	");
		code.add("	my $pathRelToInstalDir = $INSTALLDIR . '/' . $pathFromUser;");
		code.add("	");
		code.add("	my $path;");
		code.add("	");
		code.add("	# ist der Pfad absolut?");
		code.add("	if($pathFromUser =~ m/^\\//)");
		code.add("	{");
		code.add("		if (stat $pathFromUser)");
		code.add("		{");
		code.add("			$path = $pathFromUser;");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			&logit('error', 'cannot read file ' . $pathFromUser);");
		code.add("			exit(1);");
		code.add("		}");
		code.add("	}");
		code.add("	# ist der Pfad relativ?");
		code.add("	else");
		code.add("	{");
		code.add("		if (stat $pathRelToInstalDir)");
		code.add("		{");
		code.add("			$path = $pathRelToInstalDir;");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			&logit('error', 'cannot read file ' . $pathRelToInstalDir);");
		code.add("			exit(1);");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	my %userConfig = getvars($path);");
		code.add("	$ALLCONFS{$label} = \\%userConfig;");
		code.add("	");
		code.add("	# pfade auf absolut erweitern");
		code.add("	expandConfigToPath($label);");
		code.add("	");
		code.add("	");
		code.add("}");

		this.code_readconf = code;
	}

	private void initCodeExpandConfigToPath()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub expandConfigToPath");
		code.add("{");
		code.add("	my $label = shift;");
		code.add("");
		code.add("	logit(\"debug\", \"expanding config parameter (\" . $label . \") to absolute path\");");
		code.add("	foreach my $param (sort keys %{$ALLCONFS{$label}})");
		code.add("	{");
		code.add("	# gibts da ein file? Ja? Dann soll auf den absoluten Pfad expandiert werden");
		code.add("		if (((${$ALLCONFS{$label}}{$param} ne \"\") && (stat $bindir.\"/\".${$ALLCONFS{$label}}{$param})))");
		code.add("		{");
		code.add("			my $orgValue = ${$ALLCONFS{$label}}{$param};");
		code.add("			${$ALLCONFS{$label}}{$param} = File::Spec->rel2abs($bindir.\"/\".${$ALLCONFS{$label}}{$param});");
		code.add("			logit(\"debug\", \"parameter $param (value=\" . $orgValue .\") expanding to (new_value=\".${$ALLCONFS{$label}}{$param}.\")\");");
		code.add("		}");
		code.add("	}");
		code.add("}");

		this.code_expandConfigToPath = code;
	}

	private void initCodeSwitchConf()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub switchConf");
		code.add("{");
		code.add("	my $label = shift;");
		code.add("	");
		code.add("	if(grep {$_ eq $label} keys %ALLCONFS)");
		code.add("	{");
		code.add("		$SELECTED_CONF_LABEL = $label;");
		code.add("	}");
		code.add("	else");
		code.add("	{");
		code.add("		&logit('error', 'config labeled ' . $label . ' is unknown. use one of these: ' . join(', ', keys %ALLCONFS));");
		code.add("	}");
		code.add("}");
		code.add("");

		this.code_switchconf = code;
	}

	private void initCodeGetvars()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub getvars");
		code.add("{");
		code.add("    my $fp_conf = shift;");
		code.add("");
		code.add("    my %CONF;");
		code.add("    if (!open (CONF, \"<$fp_conf\")) {die \"cannot read $fp_conf $!\\n\";}");
		code.add("    ");
		code.add("    while(<CONF>)");
		code.add("    {");
		code.add("        if    ( $_ =~ m/^#/) {next}");
		code.add("        elsif ( $_ =~ m/^$/) {next}");
		code.add("		elsif ( $_ =~ m/^\\s*$/) {next}");
		code.add("        else");
		code.add("        {");
		code.add("            my @tmp = split('=', $_);");
		code.add("            ");
		code.add("        	# falls unwahr, soll der parameter einen leeren string erhalten");
		code.add("        	unless ($tmp[1]) {$tmp[1] = '';}");
		code.add("        	");
		code.add("        	$tmp[0] =~ s/\\s$//g;");
		code.add("        	$tmp[0] =~ s/^\\s//g;");
		code.add("        	$tmp[1] =~ s/\\s$//g;");
		code.add("        	$tmp[1] =~ s/^\\s//g;");
		code.add("        			");
		code.add("            $CONF{$tmp[0]} = $tmp[1];");
		code.add("        }");
		code.add("    }");
		code.add("    close CONF;");
		code.add("    return %CONF;");
		code.add("}");

		this.code_getvars = code;
	}

	private void initCodeInitlist()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub initlist");
		code.add("{");
		code.add("	if(scalar(@_) != 10)");
		code.add("	{");
		code.add("		&logit(\"fatal\", \"initlist needs exact 10 (not \".scalar(@_).\") parameters (1=type 2=returnfield 3=fromstep 4=insertrule 5=minoccur 6=maxoccur 7=refARRAYmatch 8=refARRAYlist 9=refARRAYvariable 10=refARRAYfile\");");
		code.add("		&logit(\"debug\", \"fromobjecttype=$_[0] returnfield=$_[1] fromstep=$_[2] insertrule=$_[3] minoccur=$_[4] maxoccur=$_[5] refARRAYmatch=$_[6] refARRAYlist=$_[7] refARRAYvariable=$_[8] refARRAYfile=$_[9]\");");
		code.add("		exit(1);");
		code.add("	}");
		code.add("");
		code.add("	my $fromobjecttype = shift;");
		code.add("	my $returnfield = shift;");
		code.add("	my $fromstep = shift;");
		code.add("	my $insertrule = shift;");
		code.add("	my $minoccur = shift;");
		code.add("	my $maxoccur = shift;");
		code.add("	my $refa_match = shift;");
		code.add("	my $refa_list = shift;");
		code.add("	my $refa_variable = shift;");
		code.add("	my $refa_file = shift;");
		code.add("	");
		code.add("	logit(\"debug\", \"- initialisierung startet\");");
		code.add("	# wenns eine variable ist");
		code.add("	if ($fromobjecttype =~ m/^variable$/i)");
		code.add("	{");
		code.add("		# flag ob liste bei insertrule=overwrite initial geleert wurde");
		code.add("		my $initialeLeerung = 0;");
		code.add("");
		code.add("		");
		code.add("		logit(\"debug\", \"-- in der aktuellen initialisierung sollen nur variablen beruecksichtigt werden.\");");
		code.add("		# auf jedes key=value Paarung sollen alle matches angewendet werden");
		code.add("		foreach my $refa_optionPair (@$refa_variable)");
		code.add("		{");
		code.add("			my $key = $$refa_optionPair[0];");
		code.add("			my $value = $$refa_optionPair[1];");
		code.add("			");
		code.add("			logit(\"debug\", \"--- variable $key=$value soll auf alle matches passen\");");
		code.add("");
		code.add("			my $doesItMatch = 1;");
		code.add("			");
		code.add("			foreach my $refh_match (@$refa_match)");
		code.add("			{");
		code.add("				my %match = %$refh_match;");
		code.add("				");
		code.add("				if($match{'field'} eq \"key\")");
		code.add("				{");
		code.add("					logit(\"debug\", \"---- passt das? $key =~ m/$match{'pattern'}/\");");
		code.add("					if ($key =~ m/$match{'pattern'}/)");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- JA\");");
		code.add("					}");
		code.add("					else");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- NEIN, Abbruch der Matchueberpruefung fuer die aktuelle Variable\");");
		code.add("						$doesItMatch = 0;");
		code.add("						last;");
		code.add("					}");
		code.add("				}");
		code.add("				elsif($match{'field'} eq \"value\")");
		code.add("				{");
		code.add("					logit(\"debug\", \"---- passt das? $value =~ m/$match{'pattern'}/\");");
		code.add("					if ($value =~ m/$match{'pattern'}/)");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- JA\");");
		code.add("					}");
		code.add("					else");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- NEIN, Abbruch der Matchueberpruefung fuer die aktuelle Variable\");");
		code.add("						$doesItMatch = 0;");
		code.add("						last;");
		code.add("					}");
		code.add("				}");
		code.add("			}");
		code.add("			");
		code.add("			if ($doesItMatch)");
		code.add("			{");
		code.add("			");
		code.add("				# wenn insertrule eq 'append'");
		code.add("				if ($insertrule eq \"append\")");
		code.add("				{");
		code.add("					# und returnfield eq 'key'");
		code.add("					if ($returnfield eq \"key\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt: \" . $key);");
		code.add("						push (@$refa_list, $key);");
		code.add("					}");
		code.add("					elsif ($returnfield eq \"value\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt: \" . $value);");
		code.add("						push (@$refa_list, $value);");
		code.add("					}");
		code.add("				}");
		code.add("				# wenn insertrule eq 'unique'");
		code.add("				if ($insertrule eq \"unique\")");
		code.add("				{");
		code.add("	");
		code.add("					# und returnfield eq 'key'");
		code.add("					if (($returnfield eq \"key\") && (!(grep { $_ eq $key } @$refa_list)))");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $key);");
		code.add("						push (@$refa_list, $key);");
		code.add("					}");
		code.add("					elsif (($returnfield eq \"value\") && (!(grep { $_ eq $value } @$refa_list)))");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $value);");
		code.add("						push (@$refa_list, $value);");
		code.add("					}");
		code.add("				}");
		code.add("				# wenn insertrule eq 'overwrite'");
		code.add("				elsif ($insertrule eq \"overwrite\")");
		code.add("				{");
		code.add("					# liste leeren, da dies der erste wert ist, der passend gefunden wurde");
		code.add("					unless($initialeLeerung)");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ evtl. vorhandene werte werden aus der liste geloescht\");");
		code.add("						@$refa_list = ();");
		code.add("						$initialeLeerung = 1;");
		code.add("					}");
		code.add("");
		code.add("					# und returnfield eq 'key'");
		code.add("					if ($returnfield eq \"key\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $key);");
		code.add("						push (@$refa_list, $key);");
		code.add("					}");
		code.add("					elsif ($returnfield eq \"value\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $value);");
		code.add("						push (@$refa_list, $value);");
		code.add("					}");
		code.add("				}");
		code.add("			}");
		code.add("		}");
		code.add("	}");
		code.add("		");
		code.add("	# wenns ein file ist");
		code.add("	elsif ($fromobjecttype =~ m/^file$/i)");
		code.add("	{");
		code.add("		# flag ob liste bei insertrule=overwrite initial geleert wurde");
		code.add("		my $initialeLeerung = 0;");
		code.add("");
		code.add("		");
		code.add("		logit(\"debug\", \"-- in der aktuellen initialisierung sollen nur files beruecksichtigt werden.\");");
		code.add("		# auf jedes key=value Paarung sollen alle matches angewendet werden");
		code.add("		foreach my $refa_optionPair (@$refa_file)");
		code.add("		{");
		code.add("			my $key = $$refa_optionPair[0];");
		code.add("			my $absfilename = $$refa_optionPair[1];");
		code.add("			");
		code.add("			logit(\"debug\", \"--- file $key=$absfilename soll auf alle matches passen\");");
		code.add("");
		code.add("			my $doesItMatch = 1;");
		code.add("			");
		code.add("			foreach my $refh_match (@$refa_match)");
		code.add("			{");
		code.add("				my %match = %$refh_match;");
		code.add("				");
		code.add("				if($match{'field'} eq \"key\")");
		code.add("				{");
		code.add("					logit(\"debug\", \"---- passt das? $key =~ m/$match{'pattern'}/\");");
		code.add("					if ($key =~ m/$match{'pattern'}/)");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- JA\");");
		code.add("					}");
		code.add("					else");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- NEIN, Abbruch der Matchueberpruefung fuer das aktuelle File\");");
		code.add("						$doesItMatch = 0;");
		code.add("						last;");
		code.add("					}");
		code.add("				}");
		code.add("				elsif($match{'field'} eq \"absfilename\")");
		code.add("				{");
		code.add("					logit(\"debug\", \"---- passt das? $absfilename =~ m/$match{'pattern'}/\");");
		code.add("					if ($absfilename =~ m/$match{'pattern'}/)");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- JA\");");
		code.add("					}");
		code.add("					else");
		code.add("					{");
		code.add("						logit(\"debug\", \"----- NEIN, Abbruch der Matchueberpruefung fuer das aktuelle File\");");
		code.add("						$doesItMatch = 0;");
		code.add("						last;");
		code.add("					}");
		code.add("				}");
		code.add("			}");
		code.add("			");
		code.add("			if ($doesItMatch)");
		code.add("			{");
		code.add("			");
		code.add("				# wenn insertrule eq 'append'");
		code.add("				if ($insertrule eq \"append\")");
		code.add("				{");
		code.add("					# und returnfield eq 'key'");
		code.add("					if ($returnfield eq \"key\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt: \" . $key);");
		code.add("						push (@$refa_list, $key);");
		code.add("					}");
		code.add("					elsif ($returnfield eq \"absfilename\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt: \" . $absfilename);");
		code.add("						push (@$refa_list, $absfilename);");
		code.add("					}");
		code.add("				}");
		code.add("# wenn insertrule eq 'unique'");
		code.add("if ($insertrule eq \"unique\")");
		code.add("{");
		code.add("	");
		code.add("	# und returnfield eq 'key'");
		code.add("	if (($returnfield eq \"key\") && (!(grep { $_ eq $key } @$refa_list)))");
		code.add("	{");
		code.add("		logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $key);");
		code.add("		push (@$refa_list, $key);");
		code.add("	}");
		code.add("	elsif (($returnfield eq \"absfilename\") && (!(grep { $_ eq $absfilename } @$refa_list)))");
		code.add("	{");
		code.add("		logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $absfilename);");
		code.add("		push (@$refa_list, $absfilename);");
		code.add("	}");
		code.add("}");
		code.add("				# wenn insertrule eq 'overwrite'");
		code.add("				elsif ($insertrule eq \"overwrite\")");
		code.add("				{");
		code.add("					# liste leeren, da dies der erste wert ist, der passend gefunden wurde");
		code.add("					unless($initialeLeerung)");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ evtl. vorhandene werte werden aus der liste geloescht\");");
		code.add("						@$refa_list = ();");
		code.add("						$initialeLeerung = 1;");
		code.add("					}");
		code.add("");
		code.add("					# und returnfield eq 'key'");
		code.add("					if ($returnfield eq \"key\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $key);");
		code.add("						push (@$refa_list, $key);");
		code.add("					}");
		code.add("					elsif ($returnfield eq \"absfilename\")");
		code.add("					{");
		code.add("						logit(\"debug\", \"------ dieser string wird an die liste angehaengt, weil er noch nicht vorhanden ist: \" . $absfilename);");
		code.add("						push (@$refa_list, $absfilename);");
		code.add("					}");
		code.add("				}");
		code.add("			}");
		code.add("		}");
		code.add("	}");
		code.add("	# ueberpruefen ob minoccur und maxoccur eingehalten wird");
		code.add("	my $anzahl_items = scalar(@$refa_list);");
		code.add("	if ($anzahl_items < $minoccur)");
		code.add("	{");
		code.add("		my $tmp;");
		code.add("		logit(\"fatal\", \"list initializes \" . $anzahl_items . \" items. that is less than the needed $minoccur\");");
		code.add("		logit(\"debug\", \"after: fromobjecttype=$fromobjecttype\");");
		code.add("		logit(\"debug\", \"after: returnfield=$returnfield\");");
		code.add("		logit(\"debug\", \"after: fromstep=$fromstep\");");
		code.add("		logit(\"debug\", \"after: insertrule=$insertrule\");");
		code.add("		logit(\"debug\", \"after: minoccur=$minoccur\");");
		code.add("		logit(\"debug\", \"after: maxoccur=$maxoccur\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_match) {$tmp = join(\", \", @$refa_match)};");
		code.add("		logit(\"debug\", \"after: refa_match=$refa_match (\" . $tmp . \")\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_list) {$tmp = join(\", \", @$refa_list)};");
		code.add("		logit(\"debug\", \"after: refa_list=$refa_list (\" . $tmp . \")\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_variable) {$tmp = join(\", \", @$refa_variable)};");
		code.add("		logit(\"debug\", \"after: refa_variable=$refa_variable (\" . $tmp . \")\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_file) {$tmp = join(\", \", @$refa_file)};");
		code.add("		logit(\"debug\", \"after: refa_file=$refa_file (\" . $tmp . \")\");");
		code.add("");
		code.add("		exit(1);");
		code.add("	}");
		code.add("	if ($anzahl_items > $maxoccur)");
		code.add("	{");
		code.add("		my $tmp;");
		code.add("		logit(\"fatal\", \"list initializes \" . $anzahl_items . \" items. that is more than the allowed $maxoccur\");");
		code.add("		logit(\"debug\", \"after: fromobjecttype=$fromobjecttype\");");
		code.add("		logit(\"debug\", \"after: returnfield=$returnfield\");");
		code.add("		logit(\"debug\", \"after: fromstep=$fromstep\");");
		code.add("		logit(\"debug\", \"after: insertrule=$insertrule\");");
		code.add("		logit(\"debug\", \"after: minoccur=$minoccur\");");
		code.add("		logit(\"debug\", \"after: maxoccur=$maxoccur\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_match) {$tmp = join(\", \", @$refa_match)};");
		code.add("		logit(\"debug\", \"after: refa_match=$refa_match (\" . $tmp . \")\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_list) {$tmp = join(\", \", @$refa_list)};");
		code.add("		logit(\"debug\", \"after: refa_list=$refa_list (\" . $tmp . \")\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_variable) {$tmp = join(\", \", @$refa_variable)};");
		code.add("		logit(\"debug\", \"after: refa_variable=$refa_variable (\" . $tmp . \")\");");
		code.add("");
		code.add("		$tmp = \"\";");
		code.add("		if(@$refa_file) {$tmp = join(\", \", @$refa_file)};");
		code.add("		logit(\"debug\", \"after: refa_file=$refa_file (\" . $tmp . \")\");");
		code.add("");
		code.add("		exit(1);");
		code.add("	}");
		code.add("}");

		this.code_initlist = code;
	}
	
	private void initCodeGirlande()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub girlande_stepstart");
		code.add("{");
		code.add("\tmy $stepname = shift;");
		code.add("");
		code.add("\tlogit(\"info\", \"###############################################\");");
		code.add("\tlogit(\"info\", \" START PROCESS STEP: $stepname\");");
		code.add("\tlogit(\"info\", \"###############################################\");");
		code.add("}");
		code.add("sub girlande_stepend");
		code.add("{");
		code.add("\tmy $stepname = shift;");
		code.add("");
		code.add("\tlogit(\"info\", \"###############################################\");");
		code.add("\tlogit(\"info\", \"   END PROCESS STEP: $stepname\");");
		code.add("\tlogit(\"info\", \"###############################################\");");
		code.add("}");
		code.add("sub girlande_processend");
		code.add("{");
		code.add("\tlogit(\"info\", \"###############################################\");");
		code.add("\tlogit(\"info\", \"   END PROCESS\");");
		code.add("\tlogit(\"info\", \"###############################################\");");
		code.add("}");

		this.code_girlande = code;
	}
	
	private void initCodeGetsetoptionsconfigs()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub getOptionKeys");
		code.add("{");
		code.add("	return sort keys %OPT;");
		code.add("}");
		code.add("");
		code.add("sub getOption");
		code.add("{");
		code.add("	my $key = shift;");
		code.add("	");
		code.add("	# wenn option nicht existiert oder die anzahl der values innerhalb der option = 0 ist");
		code.add("	if (!(defined $OPT{$key}))");
		code.add("	{");
		code.add("		return undef;");
		code.add("	}");
		code.add("	");
		code.add("	elsif (ref($OPT{$key}) eq \"SCALAR\")");
		code.add("	{");
		code.add("		if (!defined ${$OPT{$key}})");
		code.add("		{");
		code.add("			return undef;");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			return ${$OPT{$key}}");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	elsif (ref($OPT{$key}) eq \"ARRAY\")");
		code.add("	{");
		code.add("		if ( (! @{$OPT{$key}}) || (scalar @{$OPT{$key}} == 0) )");
		code.add("		{");
		code.add("			return undef;");
		code.add("		}");
		code.add("		# wenn es genau eine value fuer die option gibt ");
		code.add("		elsif (scalar(@{$OPT{$key}}) == 1)");
		code.add("		{");
		code.add("			return ${$OPT{$key}}[0]");
		code.add("		}");
		code.add("		# wenn es mehrere values fuer die option gibt");
		code.add("		else");
		code.add("		{");
		code.add("			return @{$OPT{$key}}");
		code.add("		}");
		code.add("	}");
		code.add("}");
		code.add("");
		code.add("sub setOption");
		code.add("{");
		code.add("	my $key = shift;");
		code.add("	");
		code.add("	if (ref($OPT{$key}) eq \"SCALAR\")");
		code.add("	{");
		code.add("		if (@_ > 1)");
		code.add("		{");
		code.add("			&logit(\"error\", \"cannot apply a list (@_) to a scalar option ($key).\");");
		code.add("		}");
		code.add("		");
		code.add("		else");
		code.add("		{");
		code.add("			${$OPT{$key}} = $_[0];");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	elsif (ref($OPT{$key}) eq \"ARRAY\")");
		code.add("	{");
		code.add("		@{$OPT{$key}} = @_;");
		code.add("	}");
		code.add("}");
		code.add("");
		code.add("sub addOption");
		code.add("{");
		code.add("	my $key = shift;");
		code.add("	");
		code.add("	if (ref($OPT{$key}) eq \"ARRAY\")");
		code.add("	{");
		code.add("		push @{$OPT{$key}}, @_;");
		code.add("	}");
		code.add("}");
		code.add("");
		code.add("sub getConfigKeys");
		code.add("{");
		code.add("	my @keys;");
		code.add("	if(@_)");
		code.add("	{");
		code.add("		my $pattern = shift @_;");
		code.add("		@keys = grep { $_ =~ m/$pattern/}sort keys %{$ALLCONFS{$SELECTED_CONF_LABEL}};");
		code.add("	}");
		code.add("	else");
		code.add("	{");
		code.add("		@keys = sort keys %{$ALLCONFS{$SELECTED_CONF_LABEL}};");
		code.add("	}");
		code.add("	");
		code.add("	return @keys;");
		code.add("}");
		code.add("");
		code.add("sub getConfig");
		code.add("{");
		code.add("	my $key = shift;");
		code.add("	if (defined ${$ALLCONFS{$SELECTED_CONF_LABEL}}{$key})");
		code.add("	{");
		code.add("		return ${$ALLCONFS{$SELECTED_CONF_LABEL}}{$key};");
		code.add("	}");
		code.add("}");
		code.add("");
		code.add("sub setConfig");
		code.add("{");
		code.add("	my $key = shift;");
		code.add("	my $value = shift;");
		code.add("	");
		code.add("	${$ALLCONFS{$SELECTED_CONF_LABEL}}{$key} = $value;");
		code.add("}");
		code.add("");
		code.add("sub importOptionToHash");
		code.add("{");
		code.add("	");
		code.add("	my $type = shift;");
		code.add("	my $refh_HASH = shift;");
		code.add("	my $option = shift;");
		code.add("	");
		code.add("	logit('debug', \"importing option $option into process-specific $type-category into step root\");");
		code.add("	");
		code.add("	# wenn es ein file ist, soll der pfad expanded werden");
		code.add("	if( $type eq 'file' )");
		code.add("	{");
		code.add("		my @allValuesOfACertainOption;");
		code.add("		");
		code.add("		# die option --commitfiledummy muss besonders behandelt werden");
		code.add("		if($option eq 'commitfiledummy')");
		code.add("		{");
		code.add("			my $key = undef;");
		code.add("			my $value = undef;");
		code.add("			");
		code.add("			if(getOption($option))");
		code.add("			{");
		code.add("				@allValuesOfACertainOption = getOption($option);");
		code.add("			}");
		code.add("			foreach my $actValue (@allValuesOfACertainOption)");
		code.add("			{");
		code.add("				my @actValue = split('=', $actValue);");
		code.add("				if(@actValue>1)");
		code.add("				{");
		code.add("					$key = shift @actValue;");
		code.add("					$value = join('=', @actValue);");
		code.add("				}");
		code.add("				else");
		code.add("				{");
		code.add("					$key = shift @actValue;");
		code.add("					$value = $key;");
		code.add("				}");
		code.add("				if(stat $value)");
		code.add("				{");
		code.add("					push(@{$$refh_HASH{'root'}}, [$key, File::Spec->rel2abs($value)]);");
		code.add("				}");
		code.add("				else");
		code.add("				{");
		code.add("					logit('error', \"option $option has to be a file. file not found: $value\");");
		code.add("					exit(1)");
		code.add("				}");
		code.add("			}");
		code.add("		}");
		code.add("		# alle anderen options");
		code.add("		else");
		code.add("		{");
		code.add("			if(getOption($option))");
		code.add("			{");
		code.add("				@allValuesOfACertainOption = getOption($option);");
		code.add("			}");
		code.add("			foreach my $actValue (@allValuesOfACertainOption)");
		code.add("			{");
		code.add("				if(stat $actValue)");
		code.add("				{");
		code.add("					push(@{$$refh_HASH{'root'}}, [$option, File::Spec->rel2abs($actValue)]);");
		code.add("				}");
		code.add("				else");
		code.add("				{");
		code.add("					logit('error', \"option $option has to be a file. file not found: $actValue\");");
		code.add("					exit(1)");
		code.add("				}");
		code.add("			}");
		code.add("		}");
		code.add("	}");
		code.add("	# wenn es eine variable ist, einfach uebernehmen");
		code.add("	elsif( $type eq 'variable' )");
		code.add("	{");
		code.add("		my @allValuesOfACertainOption;");
		code.add("		");
		code.add("		# die option --commitvariabledummy muss besonders behandelt werden");
		code.add("		if($option eq 'commitvariabledummy')");
		code.add("		{");
		code.add("			my $key = undef;");
		code.add("			my $value = undef;");
		code.add("			");
		code.add("			if(getOption($option))");
		code.add("			{");
		code.add("				@allValuesOfACertainOption = getOption($option);");
		code.add("			}");
		code.add("			foreach my $actValue (@allValuesOfACertainOption)");
		code.add("			{");
		code.add("				my @actValue = split('=', $actValue);");
		code.add("				if(@actValue>1)");
		code.add("				{");
		code.add("					$key = shift @actValue;");
		code.add("					$value = join('=', @actValue);");
		code.add("				}");
		code.add("				else");
		code.add("				{");
		code.add("					$key = shift @actValue;");
		code.add("					$value = $key;");
		code.add("				}");
		code.add("				push(@{$$refh_HASH{'root'}}, [$key, File::Spec->rel2abs($value)]);");
		code.add("			}");
		code.add("		}");
		code.add("		# alle anderen options");
		code.add("		else");
		code.add("		{");
		code.add("			if(getOption($option))");
		code.add("			{");
		code.add("				@allValuesOfACertainOption = getOption($option);");
		code.add("			}");
		code.add("			foreach my $actValue (@allValuesOfACertainOption)");
		code.add("			{");
		code.add("				push(@{$$refh_HASH{'root'}}, [$option, $actValue]);");
		code.add("			}");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	else");
		code.add("	{");
		code.add("		logit('fatal', \"unknown type $type. only permitted one of these: variable OR file\");");
		code.add("		exit(1);");
		code.add("	}");
		code.add("	");
		code.add("}");
		code.add("");
		code.add("sub addFilesEtc");
		code.add("{");
		code.add("	my $refh_FILE = shift;");
		code.add("	");
		code.add("# existiert ein etc-verzeichnis?");
		code.add("	if(-d $etcdir)");
		code.add("	{");
		code.add("		# filesliste des etc-directories ermitteln");
		code.add("		opendir(ETC, $etcdir);");
		code.add("		my @fileOfEtc = grep{ $_ !~ m/^\\./ } readdir(ETC);");
		code.add("		");
		code.add("		&logit(\"debug\", \"adding \" . scalar(@fileOfEtc) . \" files from <installdir>/etc to list 'installetc' of step 'root'\");");
		code.add("		");
		code.add("		foreach my $fileOfEtc (@fileOfEtc)");
		code.add("		{");
		code.add("			push(@{$$refh_FILE{'root'}}, [\"subdiretc\", File::Spec->rel2abs($etcdir . \"/\" . $fileOfEtc)]);");
		code.add("			&logit(\"debug\", \"adding to 'root': subdiretc=\" . File::Spec->rel2abs($etcdir . \"/\" . $fileOfEtc));");
		code.add("		}");
		code.add("	}");
		code.add("	else");
		code.add("	{");
		code.add("		&logit(\"debug\", \"kein etc-verzeichnis vorhanden -> es werden keine etc-dateien in den root-step importiert\");");
		code.add("	}");
		code.add("}");
		code.add("");
		code.add("");

//		code.add("sub expandPathInOptions");
//		code.add("{");
//		code.add("	foreach my $key (getOptionKeys())");
//		code.add("	{");
//		code.add("		if (ref($OPT{$key}) eq \"SCALAR\")");
//		code.add("		{");
//		code.add("			if ((${$OPT{$key}}) && (stat ${$OPT{$key}}))");
//		code.add("			{");
//		code.add("				&logit(\"info\", \"expanding path of the value of option $key\");");
//		code.add("				&logit(\"info\", ${$OPT{$key}} . \" -> \" . File::Spec->rel2abs(${$OPT{$key}}));");
//		code.add("				${$OPT{$key}} = File::Spec->rel2abs(${$OPT{$key}});");
//		code.add("			}");
//		code.add("		}");
//		code.add("		");
//		code.add("		elsif (ref($OPT{$key}) eq \"ARRAY\")");
//		code.add("		{");
//		code.add("			for(my $x=0; $x<scalar(@{$OPT{$key}}); $x++)");
//		code.add("			{");
//		code.add("				if ((${$OPT{$key}}[$x]) && (stat ${$OPT{$key}}[$x]) )");
//		code.add("				{");
//		code.add("					&logit(\"info\", \"expanding path of value of option $key\");");
//		code.add("					&logit(\"info\", ${$OPT{$key}}[$x] . \" -> \" . File::Spec->rel2abs(${$OPT{$key}}[$x]));");
//		code.add("					${$OPT{$key}}[$x] = File::Spec->rel2abs(${$OPT{$key}}[$x]);");
//		code.add("				}");
//		code.add("			}");
//		code.add("		}");
//		code.add("	}");
//		code.add("}");


		
		this.code_getsetoptionsconfigs = code;
	}
	
	private void initCodeimportinitcommits()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub importInitCommitFile");
		code.add("{");
		code.add("	my $refh_FILE = shift;");
		code.add("	my $pathString = shift;");
		code.add("	");
		code.add("	foreach my $dir (split(/:/, $pathString))");
		code.add("	{");
		code.add("		my $absDir = undef;");
		code.add("		if($dir =~ m/^\\//)");
		code.add("		{");
		code.add("			$absDir = $dir;");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			$absDir = $installdir . \"/$dir\";");
		code.add("		}");
		code.add("		");
		code.add("		if(-d $absDir)");
		code.add("		{");
		code.add("			opendir(ETC, $absDir);");
		code.add("			my @files = grep{ $_ !~ m/^\\./ } readdir(ETC);");
		code.add("			");
		code.add("			foreach my $file (@files)");
		code.add("			{");
		code.add("				unless(-d $file)");
		code.add("				{");
		code.add("					my ($filename, $directories, $suffix) = fileparse($file);");
		code.add("					&logit('debug', \"initCommitFile: adding $filename=$file to step 'root'\");");
		code.add("					push(@{$$refh_FILE{'root'}}, [$filename, $file]);");
		code.add("				}");
		code.add("			}");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			&logit('warn', 'initCommitFile: directory does not exist: ' . $absDir);");
		code.add("		}");
		code.add("	}");
		code.add("}");
		code.add("");
		code.add("sub importInitCommitVariable");
		code.add("{");
		code.add("	my $refh_VARIABLE = shift;");
		code.add("	my $pathString = shift;");
		code.add("	");
		code.add("	foreach my $dir (split(/:/, $pathString))");
		code.add("	{");
		code.add("		my $absDir = undef;");
		code.add("		if($dir =~ m/^\\//)");
		code.add("		{");
		code.add("			$absDir = $dir;");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			$absDir = $installdir . \"/$dir\";");
		code.add("		}");
		code.add("		");
		code.add("		if(-d $absDir)");
		code.add("		{");
		code.add("			opendir(ETC, $absDir);");
		code.add("			my @files = grep{ $_ !~ m/^\\./ } readdir(ETC);");
		code.add("			");
		code.add("			foreach my $file (@files)");
		code.add("			{");
		code.add("				unless(-d $file)");
		code.add("				{");
		code.add("					my ($filename, $directories, $suffix) = fileparse($file);");
		code.add("					");
		code.add("					# wenn file den namen 'variables' traegt, so soll jede zeile als variablendefinition a=b interpretiert werden");
		code.add("					# fehlt ein '=' soll schluessel und wert gleich sein");
		code.add("					if($filename =~ m/^variables$/)");
		code.add("					{");
		code.add("						open (VARFILE, '<', $file) or die \"cannot read $file: $!\";");
		code.add("						my @allLines = <VARFILE>;");
		code.add("						chomp @allLines;");
		code.add("						close VARFILE;");
		code.add("						");
		code.add("						foreach my $line (@allLines)");
		code.add("						{");
		code.add("							if( ($line =~ m/^\\s*$/) || ($line =~ m/^\\s*#/) )");
		code.add("							{");
		code.add("								next;");
		code.add("							}");
		code.add("							");
		code.add("							my @line = split(/=/, $line);");
		code.add("							");
		code.add("							my $key = 'toBeDetermined';");
		code.add("							my $value = 'toBeDetermined';");
		code.add("							");
		code.add("							if(@line > 1)");
		code.add("							{");
		code.add("								$key = shift(@line);");
		code.add("								$value = join('=', @line);");
		code.add("							}");
		code.add("							elsif(@line == 1)");
		code.add("							{");
		code.add("								$key = shift(@line);");
		code.add("								$value = $key;");
		code.add("							}");
		code.add("							");
		code.add("							# ablegen im hash");
		code.add("							&logit('debug', \"initCommitVariable: adding $key=$value to step 'root'\");");
		code.add("							push(@{$$refh_VARIABLE{'root'}}, [$key, $value]);");
		code.add("						}");
		code.add("					}");
		code.add("					# traegt die datei das namensmuster variable.<key>, soll jede ziele als variable interpretiert werden");
		code.add("					# dabei ist jedoch der schluessel immer <key>");
		code.add("					elsif($filename =~ m/^variable\\.(.+)$/)");
		code.add("					{");
		code.add("						my $key = $1;");
		code.add("						my $value = 'toBeDetermined';");
		code.add("						");
		code.add("						open (VARFILE, '<', $file) or die \"cannot read $file: $!\";");
		code.add("						my @allLines = <VARFILE>;");
		code.add("						chomp @allLines;");
		code.add("						close VARFILE;");
		code.add("						");
		code.add("						foreach my $line (@allLines)");
		code.add("						{");
		code.add("							if( ($line =~ m/^\\s*$/) || ($line =~ m/^\\s*#/) )");
		code.add("							{");
		code.add("								next;");
		code.add("							}");
		code.add("							");
		code.add("							$value = $line;");
		code.add("							");
		code.add("							# ablegen im hash");
		code.add("							&logit('debug', \"initCommitVariable: adding $key=$value to step 'root'\");");
		code.add("							push(@{$$refh_VARIABLE{'root'}}, [$key, $value]);");
		code.add("						}");
		code.add("					}");
		code.add("					else");
		code.add("					{");
		code.add("						&logit('error', \"initCommitVariable: you may not use files to transport variables with names that do not match /variables|variable\\..+/\");");
		code.add("					}");
		code.add("				}");
		code.add("			}");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			&logit('warn', 'initCommitVariable: directory does not exist: ' . $absDir);");
		code.add("		}");
		code.add("	}");
		code.add("}");

		this.code_importinitcommits = code;
	}

	private void initCodeResolve()
	{
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub resolve");
		code.add("{");
		code.add("	my $string = shift;");
		code.add("	my $refh_lists = shift;");
		code.add("	");
		code.add("	if($string =~ m/\\{\\$.+\\}/)");
		code.add("	{");
		code.add("		&logit(\"debug\", \"string has to be resolved because it contains list items ($string)\");");
		code.add("		my @mentionedLists = $string =~ /\\{\\$(.+?)\\}/g;");
		code.add("");
		code.add("		foreach my $list (@mentionedLists)");
		code.add("		{");
		code.add("#			&logit(\"debug\", \"placeholder for list '$list' will be replaced\");");
		code.add("			my $firstItemOfList = (${$$refh_lists{$list}}[0]);");
		code.add("");
		code.add("			if($string =~ s/\\{\\$$list\\}/$firstItemOfList/g)");
		code.add("			{");
		code.add("				&logit(\"debug\", \"---- substitution in call successfull: (/{\\$$list}/ => /$firstItemOfList/)\");");
		code.add("			}");
		code.add("			else");
		code.add("			{");
		code.add("				&logit(\"debug\", \"---- substitution in call NOT successfull - somethings wrong: (/{\\$$list}/ => /$firstItemOfList/)\");");
		code.add("			}");
		code.add("		}");
		code.add("	}");
		code.add("	&logit(\"debug\", \"string has been resolved to (string=$string)\");");
		code.add("");
		code.add("	return $string;");
		code.add("}");

		this.code_resolve = code;
	}
	private void initCodeCommandresolve()
	{
		
		ArrayList<String> code = new ArrayList<String>();
		
		code.add("sub commandResolve");
		code.add("{");
		code.add("	my $command = shift;");
		code.add("	");
		code.add("	my $commandCall = undef;");
		code.add("	");
		code.add("	foreach my $path (split(/:/, $PROCESS_PATH))");
		code.add("	{");
		code.add("		my $absPath = undef;");
		code.add("		if($path =~ m/^\\//)");
		code.add("		{");
		code.add("			$absPath = $path;");
		code.add("		}");
		code.add("		else");
		code.add("		{");
		code.add("			$absPath = $installdir . \"/$path\";");
		code.add("		}");
		code.add("		");
		code.add("		if(stat $absPath . '/' . $command)");
		code.add("		{");
		code.add("			&logit(\"debug\", \"command '\" . $command . \"' found command in processPath $absPath\");");
		code.add("			$commandCall = $absPath . '/' . $command;");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	unless ($commandCall)");
		code.add("	{");
		code.add("		my $which = `which $command 2> /dev/null`;");
		code.add("		my @which = split(' ', $which);");
		code.add("		");
		code.add("		if((($which[0]) && (stat $which[0])) || (stat $which))");
		code.add("		{");
		code.add("			&logit(\"debug\", \"command $command found with 'which' in shellPath\");");
		code.add("			$commandCall = $command;;");
		code.add("		}");
		code.add("	}");
		code.add("	");
		code.add("	return $commandCall;");
		code.add("}");

		this.code_commandresolve = code;
	}
	
	
}
